# Generated by Django 6.0 on 2025-12-17 05:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hokerattendance",
            name="half_time",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="purchasebooklet",
            name="start_date",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 12, 17, 5, 12, 42, 659910, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
