# Generated by Django 6.0 on 2025-12-14 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0002_newspaperdelivery"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchasenewspaper",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
