# Generated by Django 6.0 on 2025-12-17 06:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0002_hokerattendance_half_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchasebooklet",
            name="start_date",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 12, 17, 6, 31, 0, 605949, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
