# Generated by Django 6.0 on 2025-12-17 06:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0003_alter_purchasebooklet_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchasebooklet",
            name="start_date",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 12, 17, 6, 50, 5, 862265, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
