# Generated by Django 6.0 on 2025-12-17 07:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0004_alter_purchasebooklet_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchasebooklet",
            name="start_date",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 12, 17, 7, 7, 33, 700043, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
