# Generated by Django 6.0 on 2025-12-14 18:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0004_subscription"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchasebooklet",
            name="purchase_date",
        ),
        migrations.AddField(
            model_name="purchasebooklet",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="purchasebooklet",
            name="start_date",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 12, 14, 18, 17, 7, 455386, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
