# Generated by Django 6.0 on 2025-12-14 18:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0005_remove_purchasebooklet_purchase_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchasebooklet",
            name="start_date",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 12, 14, 18, 41, 4, 689406, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
