# Generated by Django 6.0 on 2025-12-17 08:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0007_alter_purchasebooklet_start_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchasebooklet",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="purchasebooklet",
            name="start_date",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 12, 17, 8, 3, 57, 791372, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="purchasenewspaper",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
