# Generated by Django 6.0 on 2025-12-15 05:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0008_alter_purchasebooklet_start_date_delete_subscription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchasebooklet",
            name="start_date",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 12, 15, 5, 10, 47, 719218, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
