# Generated by Django 6.0 on 2025-12-17 08:50

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("customer", "0008_alter_purchasebooklet_is_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchasebooklet",
            name="start_date",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 12, 17, 8, 50, 3, 958629, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.CreateModel(
            name="MonthlyBill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.PositiveIntegerField()),
                ("year", models.PositiveIntegerField()),
                (
                    "days_on_delivery",
                    models.JSONField(
                        help_text="List of days when newspaper was delivered (e.g. [1,2,5,10])"
                    ),
                ),
                ("total_delivery_days", models.PositiveIntegerField(default=0)),
                (
                    "base_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount without late charges",
                        max_digits=8,
                    ),
                ),
                (
                    "late_charges",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=8)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_submit_date", models.DateField()),
                ("is_paid", models.BooleanField(default=False)),
                ("paid_on", models.DateTimeField(blank=True, null=True)),
                ("remarks", models.CharField(blank=True, max_length=200)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_bills",
                        to="accounts.agentprofile",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bills",
                        to="accounts.customerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "-month"],
                "unique_together": {("customer", "month", "year")},
            },
        ),
    ]
