# Generated by Django 6.0 on 2025-12-15 06:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0009_alter_purchasebooklet_start_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newspaperdelivery",
            name="purchase",
        ),
        migrations.AlterField(
            model_name="purchasebooklet",
            name="start_date",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 12, 15, 6, 24, 43, 361948, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
