# Generated by Django 6.0 on 2025-12-15 07:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0010_remove_newspaperdelivery_purchase_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchasebooklet",
            name="start_date",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 12, 15, 7, 32, 28, 915387, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
