# Generated by Django 5.0.6 on 2025-12-20 07:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0010_alter_agentpayment_id_alter_allotedhoker_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchasebooklet",
            name="start_date",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 12, 20, 7, 32, 53, 761514, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
