# Generated by Django 5.0.6 on 2025-12-20 10:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0011_alter_purchasebooklet_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchasebooklet",
            name="start_date",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 12, 20, 10, 54, 51, 317287, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
