# Generated by Django 6.0 on 2025-12-17 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AgentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("mobile", models.CharField(max_length=10)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("address", models.TextField()),
                ("state", models.CharField(max_length=50)),
                ("district", models.CharField(max_length=50)),
                ("tehsil", models.CharField(max_length=50)),
                ("village", models.CharField(max_length=50)),
                ("pincode", models.CharField(max_length=6)),
                ("agency_name", models.CharField(max_length=100)),
                ("agency_phone", models.CharField(max_length=10)),
                ("age", models.PositiveIntegerField()),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("photo", models.ImageField(upload_to="agents/")),
                ("password", models.CharField(max_length=150)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="HokerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("mobile", models.CharField(max_length=10)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("address", models.TextField()),
                ("state", models.CharField(max_length=50)),
                ("district", models.CharField(max_length=50)),
                ("tehsil", models.CharField(max_length=50)),
                ("village", models.CharField(max_length=50)),
                ("pincode", models.CharField(max_length=6)),
                ("age", models.PositiveIntegerField()),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="hokers/"),
                ),
                ("password", models.CharField(max_length=150)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="CustomerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("surname", models.CharField(max_length=100)),
                ("mobile", models.CharField(max_length=10)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("address", models.TextField()),
                ("state", models.CharField(max_length=50)),
                ("district", models.CharField(max_length=50)),
                ("tehsil", models.CharField(max_length=50)),
                ("village", models.CharField(max_length=50)),
                ("pincode", models.CharField(max_length=6)),
                ("age", models.PositiveIntegerField()),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("photo", models.ImageField(upload_to="")),
                ("password", models.CharField(default="", max_length=150)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customers",
                        to="accounts.agentprofile",
                    ),
                ),
            ],
        ),
    ]
