# Generated by Django 6.0 on 2025-12-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_customerprofile_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerprofile",
            name="password",
            field=models.CharField(default="", max_length=60),
        ),
    ]
