# Generated by Django 6.0 on 2025-12-14 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_agentprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=8)),
                ("remarks", models.CharField(blank=True, max_length=200)),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.agentprofile",
                    ),
                ),
            ],
        ),
    ]
