# Generated by Django 6.0 on 2025-12-14 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_agentpayment"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AgentPayment",
        ),
    ]
