# Generated by Django 6.0 on 2025-12-15 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_delete_agentpayment"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerprofile",
            name="agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="customers",
                to="accounts.agentprofile",
            ),
        ),
    ]
