# Generated by Django 6.0 on 2025-12-15 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_customerprofile_agent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentprofile",
            name="password",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="customerprofile",
            name="password",
            field=models.CharField(default="", max_length=150),
        ),
    ]
