# Generated by Django 6.0 on 2025-12-15 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0007_customerprofile_agent"),
        ("customer", "0009_alter_purchasebooklet_start_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="AllotedCustomer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("PB", models.PositiveIntegerField(default=0)),
                ("BH", models.PositiveIntegerField(default=0)),
                ("HT", models.PositiveIntegerField(default=0)),
                ("TIMES", models.PositiveIntegerField(default=0)),
                ("HINDU", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("allotted_on", models.DateTimeField(auto_now_add=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alloted_customers",
                        to="accounts.agentprofile",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_allotments",
                        to="accounts.customerprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExtraDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                (
                    "delivery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customer.newspaperdelivery",
                    ),
                ),
                (
                    "newspaper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customer.newspaper",
                    ),
                ),
            ],
        ),
    ]
