# Generated by Django 6.0 on 2025-12-17 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("agent", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HokerDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("newspaper_present", models.BooleanField(default=False)),
                ("booklet_present", models.BooleanField(default=False)),
                ("is_delivered", models.BooleanField(default=True)),
                ("remarks", models.CharField(blank=True, max_length=200)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.customerprofile",
                    ),
                ),
                (
                    "hoker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.hokerprofile",
                    ),
                ),
            ],
            options={
                "unique_together": {("customer", "date")},
            },
        ),
    ]
