# Generated by Django 6.0 on 2025-12-17 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("agent", "0002_hokerdelivery"),
    ]

    operations = [
        migrations.AlterField(
            model_name="allotedcustomer",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.customerprofile",
            ),
        ),
    ]
