# Generated by Django 6.0 on 2025-12-17 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent", "0004_alter_allotedcustomer_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="extradelivery",
            name="delivery",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="extra_deliveries",
                to="agent.hokerdelivery",
            ),
        ),
    ]
