# Generated by Django 5.0.6 on 2025-12-20 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent", "0005_alter_extradelivery_delivery"),
    ]

    operations = [
        migrations.AlterField(
            model_name="allotedcustomer",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="extradelivery",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="hokerdelivery",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
